### ISSUE TITLE
Scene thumbnail settings hostile to other add-ons that can affect thumbnails

### ISSUE THREAD

**Issue by dstein766** [Sparkasaurusmex/OotDui#2]
I'm using an add-on that includes a selection to enable reduction of the dimensions of the thumbnails in the Scene sidebar.  MythicUI forcibly overrides those settings instead of respecting them.  I am forced to manually modify MythicUI's .css in order to have it "play nice".

Suggest these changes be incorporated into your .css:

#scenes .scene h3 {
    line-height: 43px;                    <-- rather than the current: 43px !important;
    text-shadow: 2px 1px 2px #000;
}
#scenes .scene {
    height: 48px;                          <-- rather than the current: 50px !important;  (it is the !important tag that matters...I prefer 48px but that's just a personal pref)
}

If you make these changes, someone using ONLY your .css will get the results you intended, while those that have add-ons that do their own thing will still be able to take advantage of that.

**Comment by Sparkasaurusmex** [comment]
These fixes are in next update.
