### ISSUE TITLE
MythicUI updates all the time

### ISSUE THREAD

**Issue by dstein766** [Sparkasaurusmex/OotDui#3]
Using MythicUI current as of today.  Anytime I use the "Update All" button on the Add-Ons page, MythicUI re-updates itself, even though I'm already at the current revision.  (This is particularly irksome as I'm forced to re-edit MythicUI's .css each time this happens to work around the problem I noted in Issue #2.)

**Comment by Sparkasaurusmex** [comment]
This is probably happening because you have modified the module so it updates to "correct" it.  If you modify it use a version number higher than any near future update (ie 5.0) or change the module name to something else.
